### PR TITLE
Minor updates and spell fixes for the compiler section

### PR DESCRIPTION
**Pull request by orta**
Thanks for the book, starting to touch the compiler internals myself and this is a really great overview for a lot of the internals. Thought I'd give something back 👍

### CODE REVIEW

**Comment by orta** [comment]
BTW, you _could_ use something like Danger to do spell checking on your book too on each PR, I understand what it's like to ship a book and occasionally update it so I also get it if you don't :D

**Comment by basarat** [comment]
awesome! Thanks ! :rose:

**Comment by basarat** [comment]
Just thought I'd point it out https://github.com/basarat/typescript-book/commit/b0cd95609bb73e62e53fa998651d3aedc67b4f33 

Its using this pattern : https://github.com/basarat/typescript-book/blob/master/docs/enums.md#enums-as-flags :rose: 

The compiled definition file is misleading :heart:

**Comment by orta** [comment]
ah, thanks!

**Pull request merged**
