### PR TITLE
Update node.d.ts link

### PR DESCRIPTION
**Pull request by tsasioglu**
Looks like it's been moved within in the repo, corrected link.

### CODE REVIEW

**Comment by djyde** [comment]
thx~

**Comment by blakeembrey** [comment]
This isn't the right destination. It should be in https://github.com/DefinitelyTyped/DefinitelyTyped instead. If you look at the README for TSD, it's a tool that reads DefinitelyTyped and has been deprecated for a year now.

**Comment by tsasioglu** [comment]
Good point, but where is node.d.ts in the DefinitelyTyped repo? I can't for the life of me find it. I've tried file search and Google, it doesn't seem to live in the repo any longer.

**Comment by blakeembrey** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/index.d.ts

**Comment by tsasioglu** [comment]
Thanks - https://github.com/basarat/typescript-book/pull/243

**Pull request merged**
