### PR TITLE
Use Readonly type for Props & State

### PR DESCRIPTION
**Pull request by briangonzalez**

### CODE REVIEW

**Comment by basarat** [comment]
You don't need to. Its encoded in the type definitions :rose:

**Comment by basarat** [comment]
Try: 

```ts
import * as React from 'react';
export class Something extends React.Component<{ foo: number }, { baz: number }> {
  // You can rest assured no one is going to do
  someMethod() {
    this.props.foo = 123; // ERROR: (props are immutable)
    this.state.baz = 456; // ERROR: (one should use this.setState)  
  }
}
```

**Comment by briangonzalez** [comment]
@basarat I don't understand why this PR was closed. You say it's "encoded in the type definitions", but my PR removes those type definitions in favor of using `Readonly<T>`.

For example, take a larger prop def:

```ts
interface Props {
  readonly foo: string
  readonly bar: string
  readonly baz: string
  readonly qux: string
  readonly dot: string
  readonly nok: string
}
```

I would argue that the following is more readable and is more intention-revealing:

```ts
interface Props extends Readonly<{
  foo: string
  bar: string
  baz: string
  qux: string
  dot: string
  nok: string
}>
```

**Comment by basarat** [comment]
> You say it's "encoded in the type definitions",

They are encoded in the React type definitions : https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2ededd19eef535f0b65e372d2f2ca28034746c0e/types/react/index.d.ts#L299-L300 

If you do what you are suggesting you get `Readonly<Readonly<Props>>` :rose:

**Comment by briangonzalez** [comment]
Oh, I see. Nice.

Then why does your book recommend marking properties as `readonly` on `State` and `Props`?

**Comment by basarat** [comment]
> Then why does your book recommend marking properties as readonly on State and Props?

Old code. A PR fixing that would be nicer :rose: :heart:

**Comment by basarat** [comment]
> A PR fixing that would be nicer 🌹 ❤️

Nevermind. I'll fix it myself :rose:

**Comment by briangonzalez** [comment]
Ok. We could have arrived at this solution much sooner if you would have said that in the first place.

**Comment by basarat** [comment]
> We could have arrived at this solution much sooner if you would have said that in the first place.

I didn't know I had that bug :rose:

**Pull request closed without merging**
