### PR TITLE
Fix pdf build issue

### PR DESCRIPTION
**Pull request by sunny4381**

### CODE REVIEW

**Review by linco95 — APPROVED** [review]
Would love to be able to get the ebook build running again, so I can read this book easier!

**Comment by mayrhofer-simon** [comment]
Is it working again

**Comment by sunny4381** [comment]
@mayrhofer-simon Yeah, you can see how it work in my repo: https://github.com/sunny4381/typescript-book/actions/runs/1200571871

**Comment by Eazash** [comment]
I believe it's now safe to also remove line 18, `sudo apt update`

**Comment by ivanbozhkov** [comment]
Can someone merge this, please?

**Pull request merged**
