### PR TITLE
Add types to tagged template example

### PR DESCRIPTION
**Pull request by Gerrit0**
Should this PR also update the code in code/es6/template-strings.ts?

### CODE REVIEW

**Comment by basarat** [comment]
The placeholders can be `any` e.g. 

```ts
const x = 'hello'
const y = 123

const foo = (strings: TemplateStringsArray, ...placeholders: any[]) => {
    return ''
}
const z = foo`${x} ${y}`
```
I'll fix post merge. Thanks :rose:

**Comment by basarat** [comment]
I've used your code and added more docs. Reason why the types were not there : The original section was supposed to be a JS premier ... a use case becoming more and more rare as people already accept the value of TypeScript :rose:

**Comment by Gerrit0** [comment]
>The placeholders can be `any` e.g.

True, though in my experience it's more valuable to limit the type - typescript will then warn if I try to use something that isn't handled by the template tag.

**Comment by basarat** [comment]
> True, though in my experience it's more valuable to limit the type - typescript will then warn if I try to use something that isn't handled by the template tag.

:+1: :rose:

**Pull request merged**
