### PR TITLE
cleared up concept of constructor

### PR DESCRIPTION
**Pull request by spencer1573**
in the text it made it sound like constructor was optional in this case and it is not.  Just wanted to clear that up for the next guy.

### CODE REVIEW

**Comment by blakeembrey** [comment]
It's not optional because of the accepted arguments needed (`x` and `y`). Do you think it's better to point that out?

**Comment by spencer1573** [comment]
of course. i just didn't know how to word it. the way it was it just sounded like the constructor was unnecessary which sounded wrong so i tested out the code and of course it didn't compile correctly.

**Comment by basarat** [comment]
Added an explicit section about it to prevent any confusion https://github.com/basarat/typescript-book/blob/master/docs/classes.md#constructor-is-optional :rose:

**Comment by spencer1573** [comment]
awesome!

**Pull request closed without merging**
