### PR TITLE
Fix safe integer example.

### PR DESCRIPTION
**Pull request by rsamuelklatchko**

### CODE REVIEW

**Comment by basarat** [comment]
The objective was to show that anything greater than `+-1` would clamp to `+-1`. I know its different from what you find elsewhere, but I try to make it easier to understand :rose:

**Comment by rsamuelklatchko** [comment]
Basarat - please take another look. The current example is actually wrong as number don't clamp at that point but lose precision. Your specific example says:

  console.log(Number.MAX_SAFE_INTEGER + 20 === Number.MAX_SAFE_INTEGER + 1); // true!

but that logs false. See https://repl.it/repls/FreshTrustworthyInvocation for an example

**Comment by basarat** [comment]
Thanks for this! :rose:

**Comment by basarat** [comment]
I confused rounding with clamping in my head. Added more info https://github.com/basarat/typescript-book/commit/765e0048a9bb315ab1c1562a7167b3643cc5738a

**Comment by rsamuelklatchko** [comment]
Hi Basarat - thanks for taking a second look.

**Pull request merged**
