### PR TITLE
Correct terminology

### PR DESCRIPTION
**Pull request by lifuhuang**
See: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

### CODE REVIEW

**Comment by basarat** [comment]
Yes, that is the correct terminology. However there is an inconsistency in the spec where `executor(resolve, reject);` but calling `reject` results in `rejected` but calling `resolve` results in `fullfilled`. 

I intentionally chose to keep it consistent with `resolved`. Don't need different names for the same concept unless there is a reason I missed :rose:

**Comment by lifuhuang** [comment]
It's true that the naming terminology used by javascript spec is confusing (calling `resolve` leads to `fulfilled`). But "fulfilled" is the only correct term in this scenario, since `resolved` has its own meaning and is NOT equivalent to "fulfilled", see [MDN][1]: 

> A promise is said to be settled if it is either fulfilled or rejected, but not pending. You will also hear the term resolved used with promises — this means that the promise is settled, or it is locked into a promise chain. Domenic Denicola's States and fates contains more details about promise terminology.

What's more, at that page of your book, you used a graph where the correct term "fulfilled" is used, which is inconsistent with your text. So I suggest adopting this PR for consistency with standard spec as well as your graph. 

[1]: https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md

**Comment by basarat** [comment]
Better to go with official and correct instead of trying to come up with a simpler explanation :) :rose:

**Comment by lifuhuang** [comment]
Probably no one can explain javascript, you can only get used to it ;) 

P.S. Thank you for the great book 👍

**Pull request merged**
