### PR TITLE
Update command to install node typings

### PR DESCRIPTION
**Pull request by sthadka**
Fix to account for changes to typings API

### CODE REVIEW

**Comment by basarat** [comment]
@blakeembrey this the recommended way now? :rose:

**Comment by blakeembrey** [comment]
Yes, that works 👍 There's also `env~node` since there's `node` in the Typings registry. Would be good to reconcile them when possible.

**Comment by basarat** [comment]
what do you feel is **recommended** :)

**Comment by blakeembrey** [comment]
I would recommend `env~node` currently.

**Pull request merged**
